### ISSUE TITLE
For adaptive localization output calculated correlations

### ISSUE THREAD

**Issue by oyvindeide** [equinor/iterative_ensemble_smoother#208]
Make an optional datastructure that can output the calculated correlations in adaptive localization.

**Comment by oyvindeide** [comment]
@dafeda suggested we look to for example: https://github.com/bayesian-optimization/BayesianOptimization/blob/master/examples/advanced-tour.ipynb for inspiration on how to do this. They have a system of callbacks. We discussed it a bit, and this should be optional, as we probably dont want to do this for fields for examples.

**Comment by tommyod** [comment]
Some thoughts on this:
- A callback seems like a good option! I imagine either `assimilate(..., corr_callback=None)` or a new method `subscribe` where we take inspiration from BayesianOptimization.
- The callback could have signature `callback(corr_XY:ndarray)` or `callback(corr_XY:ndarray, threshold:float)`. The caller then stores this information to disk within the callback function, or does something else with it.


This seems simple to implement. But beware that `corr_XY` can be huge, and that each entry is subject to a lot of noise since the number of realizations is so small.

**Comment by dafeda** [comment]
Want to fix #7941 first
